config/routes.rb
Awad::Application.routes.draw do

  resources :users

  resources :search

  resources :sessions, only: [:new, :create, :destroy]

  root :to => 'users#welcome'

  match '/signup', to: 'users#new'
  match '/login',  to: 'sessions#new'
  match '/logout', to: 'sessions#destroy', via: :delete

end

app/models/school.rb
class School < ActiveRecord::Base
  attr_accessible :uprn, :blpu_class, :name, :street, :postcode, :xref, :yref, :address, :school_group
	def self.query(search)
	    search_condition =  "%#{search}%"
    	find(:all, :conditions => ['postcode LIKE ? OR name LIKE ?', search_condition, search_condition])
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :admin, :email, :password, :password_confirmation, :remember_token
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :email, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/, :on => :create }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  include ApplicationHelper
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	include ApplicationHelper
	include SessionsHelper
	def index
		if (params[:search]).blank?
			@schools = ""
		else
			@schools = School.query(params[:search])
		end
  	end

	def show
		postcode = params[:id]
		@place = School.where("postcode = ?", postcode)
		gon.mypostcode = params[:id]
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end

  def create
  	user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash[:error] = 'Oops! Your email/password combination is wrong'
      redirect_to root_path
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      log_in @user
      flash.now[:success] = "Account Successfully Created"
      redirect_to @user 
    else
      render "new"
    end

  end

  def edit
    @user = User.find(params[:id])
  end

   def index
    @users = User.where(:admin => nil)
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  def show
    @user = User.find(params[:id])
    @name = email_to_name(@user)
    @schools = School.find(:all)
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Update successful!"
      log_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def welcome
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def email_to_name(arg)
    split_to_array = (arg.email).split(/@/)
    @name = split_to_array[0]
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

   def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

    def current_user?(user)
    user == current_user
    end
  

  def log_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_login.html.erb
        <%= form_for(:session, url: sessions_path) do |f| %>
           <%= f.label :email, id: "email_id" %>
           <%= f.text_field :email, placeholder: "Email" %>
           <%= f.label :password, id: "pass_id" %>
           <%= f.password_field :password, placeholder: "Password" %>
           <br />
           <br />
           <%= f.submit "Log In", class: "btn" %>
        <% end %>

app/views/layouts/_search.html.erb
<div class="search_bar" >
    <%= form_tag("/search", :method => "get") do %>
    <%= label_tag(:search, "Enter Search Below") %>
    <%= text_field_tag(:search) %>
    <br />
    <br />
    <%= submit_tag("Search", class: "btn") %>
    <% end %>
    <br />
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  <title>School Finder</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"><!-- see if dis has any effect on display on mobile devices... -->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= include_gon %>
  <%= javascript_include_tag "http://maps.google.com/maps/api/js?sensor=false" %>
  <%= javascript_include_tag "http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="wrapper">
    <div class="navbar">
      <% if logged_in? %>
      <%= link_to "Home", current_user, class: "brand" %>
        <% if current_user.admin && !current_user?(:user)%>
          <%= link_to "View Profiles", users_path, class: 'brand'  %>
        <% end %>
      <%= link_to "Edit Profile", edit_user_path(current_user), class: 'brand' %>
      <%= link_to "logout", logout_path, method: "delete", class: "brand" %>
      <% else %>
      <div class="login_container">
        <%= link_to "School Finder", root_path, class: "lft brand" %>
       </div>
      <% end %>
    </div>
    <div class="hero-unit">
      <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
  <%= yield %>
    </div>
    <div id="sidebar">
      <% if logged_in? %>
        <%= render "layouts/search" %>
      <% else %>
        <%= render "layouts/login" %>
      <% end %>
    </div>
    <footer>
      <p>&copy; Your Name, Student ID</p>
    </footer>
    </div>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/search/create.html.erb
<h1>Search#create</h1>
<p>Find me in app/views/search/create.html.erb</p>

app/views/search/index.html.erb
<% if @schools.blank? %>
<h1>Your search yielded no results.</h1>
	<%= render "layouts/search" %>
<% else %>
<p>Your search returned the following items:</p>
	<div id="schools_result">
	<% @schools.each do |school| %>
	<ol>
	
	<li><%= link_to "#{school.name}", search_path("#{school.postcode}"), {style: "color: blue"} %></li>
		<li><%= school.address %></li>
		<li><%= school.school_group %></li>
	</ol>
	<% end %>
	</div>
<% end %>

app/views/search/new.html.erb
<h1>Search#new</h1>
<p>Find me in app/views/search/new.html.erb</p>

app/views/search/show.html.erb
<h1>Search Page</h1>
<p>You are viewing a map for,
	<% @place.each do |p| %>
		<%= p.name %>
	<% end %>
</p>
	<br />
     <div id="pano"></div>
    <input id="address" type="hidden" placeholder="Aberdeen">
    <input type="hidden" value="Encode" onclick="codeAddress()">
    <br />

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
	<h1>Edit Your Profile</h1>
	<%= form_for(@user) do |f| %>
		<%= render 'shared/error_messages' %>
		<%= f.label :email %>
		<%= f.text_field :email %> <br />
		<%= f.label :password %>
		<%= f.password_field :password %> <br />
		<%= f.label :password_confirmation, "Confirmation" %> 
		<%= f.password_field :password_confirmation %><br />
		<%= f.submit "Update Profile", class: "btn" %>
	<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<% provide(:title, 'All User Page') %>
<ul class="users">
	<% @users.each do |user| %>
	 <li><%= link_to "#{(email_to_name(user)).titlecase}'s Profile", user_path(user), {style: "color:blue" }  %>
     <% if current_user.admin %>
     <%= link_to " Delete Account", user, method: :delete, data: { confirm: "Are you sure?"}, class: "btn" %>
     <%= link_to " Edit Account", edit_user_path(user), class: "btn" %>
     <% end %>
     </li>
     <br />
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Create Your Account</h1>
	<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages' %>
	<%= f.label :email %>
	<%= f.text_field :email %> <br />
	<%= f.label :password %>
	<%= f.password_field :password %> <br />
	<%= f.label :password_confirmation, "Confirmation" %> 
	<%= f.password_field :password_confirmation %><br />
	<%= f.submit "Create Account", class: "btn" %>
<% end %>

app/views/users/show.html.erb
<h1><%= "#{@name.upcase}'s Profile" %></h1>
<%#= @schools %>
<div id="schools_result">
<% @schools.each do |school| %>
<ol>
	<li><%= link_to "#{school.name}", search_path("#{school.postcode}"), {style: "color: blue"} %></li>
	<li><%= school.address %></li>
	<li><%= school.school_group %></li>
</ol>
<% end %>
</div>

app/views/users/welcome.html.erb
<h1>Welcome to Aberdeen Search</h1>
<%= render "layouts/search"  %>
   <br />
   <br />
<p style="text-align: center" >Don't have an account? <br /><br /> <%= link_to "Create one now!", signup_path, class: "btn" %></p>